yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
         ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
# (главный файл url проекта)
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.core.exceptions import ValidationError


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='Слаг')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст',
                            help_text='Введите текст поста'
                            )
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:settings.TEST_LEN_TEXT]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите ваш комментарий',
        max_length=200,
    )
    pub_date = models.DateTimeField(
        'date_published',
        auto_now_add=True,
    )


class Follow(models.Model):
    # пользователь, который подписывается
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    # пользователь, на которого подписываются
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    def save(self, *args, **kwargs):
        if self.user == self.author:
            raise ValidationError('Вы не можете подписаться на себя')
        return super(Follow, self).save(*args, **kwargs)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "author"],
                                    name="unique_follow")
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import Post, Group, User, Comment, Follow
from .forms import PostForm, CommentForm


def paginator(posts, request):
    pag = Paginator(posts, settings.COUNT_POSTS)
    page_number = request.GET.get('page')
    return pag.get_page(page_number)


def index(request):
    post_list = Post.objects.select_related('author', 'group').all()
    page_obj = paginator(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author').all()
    page_obj = paginator(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group').all()
    page_obj = paginator(posts, request)
    template = 'posts/profile.html'
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post=post)
    context = {
        'post': post,
        'form': CommentForm(),
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = Post.objects.get(id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', post.id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post}
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user.id)
    page_obj = paginator(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user.username != username:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author_username = get_object_or_404(User, username=username)
    Follow.objects.filter(
        author=author_username,
        user=request.user
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
{% if is_edit %}
  Редактировать пост
{% else %}
  Новый пост
{% endif %}
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %}
          Редактировать пост
        {% else %}
          Новый пост
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row my-3 p-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
            </label>
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
            {% endif %}
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить пост
              {% endif %}
            </button>
              {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Избранные авторы
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1>Избранные авторы</h1>
    {% load cache %}
    {% cache 20 follow_page page_obj.number %}
      {% include 'posts/includes/switcher.html' with show_follow=True %}
        {% for post in page_obj %}
        {% load thumbnail %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.created|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
          </article>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock  %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{%block title %}Записи сообщества {{ group.title }} {%endblock%}
{% block content %}
<div class="container py-5">
  <h1>{{ group }}</h1>
  <p>
    {{ group.description|linebreaks }}
  </p>
  {% for post in page_obj %}
    <article>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <ul>
        <li>
          Автор:
          <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.get_full_name }}
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <li>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </li>
      </ul>
      <p>
        {{ post.text|linebreaks }}
      </p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Главная страница
{% endblock %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% load cache %}
  {% cache 20 index_page page_obj.number %}
  {% include 'posts/includes/switcher.html' with show_index=True %}
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
           <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
        {{ post.text }}
      </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </article>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
 Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% load thumbnail %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{%url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ post.author.posts.count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{%url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaks }}
      </p>
      {% if request.user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">редактировать запись</a>
      {% endif %}
      {% load user_filters %}

      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text|linebreaksbr }}
            </p>
          </div>
        </div>
      {% endfor %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }} </h1>
      <h3>Всего постов: {{ author.posts.count }} </h3>
      {% if request.user != author %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
               Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|linebreaks }}
          </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
          {% if post.group %}
            <p>
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </p>
          {% endif %}
        </article>
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}